name: Test, Build, and Deploy

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    name: Test Code, Build Docker Images, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"
  
      - name: Install Dependencies
        run: dotnet restore

      - name: Run Unit Test
        run: |
          dotnet test FoodApi.Tests/FoodApi.Tests.csproj
          dotnet test StudentsApi.Tests/StudentsApi.Tests.csproj

      - name: Build Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ocelot-gateway:latest ./ApiGateway
          docker build -t ${{ secrets.DOCKER_USERNAME }}/foodapi:latest ./FoodApi
          docker build -t ${{ secrets.DOCKER_USERNAME }}/studentsapi:latest ./StudentsApi

      - name: Integration Testing
        run: |
          dotnet test ApiGateway/IntegrationTests.csproj

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Images to DH
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ocelot-gateway:latest        
          docker push ${{ secrets.DOCKER_USERNAME }}/foodapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/studentsapi:latest

      - name: SSH to Server and Deploy Docker Containers
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSWORD }}
          port: 22
          script: |
            cd ~/ASP-Dotnet-MicroServices-CICD
            docker-compose down
            git pull
            docker-compose pull
            docker-compose up -d
